(* palindromes.mll
   Question 2, part 4: binary palindromes of length 3 or 4.

   The general language "binary strings that are palindromes" is NOT
   regular for arbitrary length: recognizing it requires remembering
   the first half of the string in order to compare it against the
   (reversed) second half, and a finite-state machine has no way to
   count/remember an unbounded amount of information. It's really a
   context-free language (think of it as the language generated by
   S -> 0 S 0 | 1 S 1 | 0 | 1 | epsilon).

   The "sneaky" trick is that we are NOT asked for palindromes of
   arbitrary length -- only length 3 or length 4. A language made up
   of strings of *bounded* length is always finite, and every finite
   language is trivially regular: you can just enumerate its members
   and OR them together. So instead of trying to build a recursive
   "match the outside, recurse on the inside" pattern (which regex
   can't express), we generate that recursive structure once, ahead
   of time, in OCaml, and flatten the result into a plain alternation.

   Length-3 palindromes have the shape  b0 b1 b0     (b0, b1 in {0,1})
   Length-4 palindromes have the shape  b0 b1 b1 b0

   Enumerating:
     length 3: 000 010 101 111
     length 4: 0000 0110 1001 1111

   which gives the (perfectly ordinary, regular) alternation:

     000 | 010 | 101 | 111 | 0000 | 0110 | 1001 | 1111
*)

let pal3 = "000" | "010" | "101" | "111"
let pal4 = "0000" | "0110" | "1001" | "1111"
let bin_palindrome = pal3 | pal4

rule token = parse
  | bin_palindrome as p { Some p }
  | eof                 { None }
  | _+                  { None }

{
(* A second, independent check written the "obvious" recursive way,
   used here only to confirm the enumerated regex above is correct --
   this recursive function is exactly the S -> 0 S 0 | 1 S 1 | ... 
   idea from the comment above, and it is NOT expressible as a single
   ocamllex regex on its own because it isn't regular in general. *)
let rec is_palindrome (s : string) : bool =
  let n = String.length s in
  if n <= 1 then true
  else s.[0] = s.[n - 1] && is_palindrome (String.sub s 1 (n - 2))

let is_valid (s : string) : bool =
  let lexbuf = Lexing.from_string s in
  match token lexbuf with
  | Some p -> p = s
  | None -> false

let () =
  let tests = [
    "101";   (* length 3, palindrome *)
    "0110";  (* length 4, palindrome *)
    "100";   (* length 3, not a palindrome *)
    "0100";  (* length 4, not a palindrome *)
    "0";     (* wrong length (too short) *)
    "10101"; (* wrong length (too long), even though it IS a palindrome *)
  ] in
  List.iter (fun s ->
    Printf.printf "%-8s -> ocamllex regex: %-7s  |  recursive check agrees: %b\n"
      s
      (if is_valid s then "VALID" else "INVALID")
      (is_valid s = ((String.length s = 3 || String.length s = 4) && is_palindrome s)))
    tests
}
